"""Skills — the only way Aura touches your Mac.

A skill is a small, declared unit of capability:

  * `SkillSpec` — name, description, argument schema, example phrasings,
    default risk. The planner sees the catalog; the safety gate trusts the
    declaration; the UI renders it.
  * `execute()` — does one thing, returns a `SkillResult`. No hidden I/O.

Everything macOS-specific lives behind `MacBridge` so skills themselves stay
readable, and so the whole layer can run in `dry-run` mode (a Linux CI box,
the demo profile, or your first cautious week) where every action is logged
instead of executed.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from typing import Any

# Skills are subprocess adapters. They must return before the orchestrator's
# five-second active-work deadline, including when macOS leaves an Automation
# consent dialog unanswered.
COMMAND_TIMEOUT_SECONDS = 4.0


@dataclass
class SkillSpec:
    name: str                    # dotted: "system.open_app"
    description: str             # planner-facing, one line
    args: dict[str, str] = field(default_factory=dict)     # arg → type hint
    examples: list[str] = field(default_factory=list)      # phrasings for the prompt
    default_risk: str = "safe"

    def catalog_line(self) -> str:
        args = ", ".join(f'{k}: {v}' for k, v in self.args.items()) or "none"
        ex = f' e.g. {" | ".join(chr(34) + e + chr(34) for e in self.examples[:2])}' if self.examples else ""
        return (f'- {self.name}({args}) — {self.description}.{ex} '
                f'[default risk: {self.default_risk}]')


@dataclass
class SkillResult:
    ok: bool
    message: str                 # human-facing, spoken or shown in the timeline
    data: dict[str, Any] = field(default_factory=dict)


class Skill:
    spec: SkillSpec

    async def execute(self, args: dict[str, Any], ctx: SkillContext) -> SkillResult:
        raise NotImplementedError


@dataclass
class SkillContext:
    bridge: MacBridge          # macOS execution surface (real or dry-run)
    memory: Any                  # aura.memory.Memory
    config: Any                  # aura.config.Config


class SkillRegistry:
    def __init__(self) -> None:
        self._skills: dict[str, Skill] = {}

    def register(self, skill: Skill) -> None:
        self._skills[skill.spec.name] = skill

    def get(self, name: str) -> Skill | None:
        return self._skills.get(name)

    def names(self) -> set[str]:
        return set(self._skills)

    def all(self) -> list[Skill]:
        return list(self._skills.values())

    def catalog_prompt(self) -> str:
        return "\n".join(s.spec.catalog_line() for s in self._skills.values())

    def specs(self) -> list[dict[str, Any]]:
        return [
            {"name": s.spec.name, "description": s.spec.description,
             "args": s.spec.args, "examples": s.spec.examples,
             "risk": s.spec.default_risk}
            for s in self._skills.values()
        ]


# --------------------------------------------------------------------------- #
# The macOS execution surface                                                  #
# --------------------------------------------------------------------------- #


def applescript_quote(value: str) -> str:
    """`value` as a safe AppleScript string literal.

    Skill args originate in the user's words (never generated by a model) and must never
    be able to break out of the literal — a stray `"` in an app name is
    otherwise an AppleScript injection (`… & (do shell script "…") & …`).
    """
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


class MacBridge:
    """Runs AppleScript/osascript + small CLI tools on a real Mac."""

    platform = "mac"

    def osascript(self, script: str) -> tuple[bool, str]:
        try:
            proc = subprocess.run(
                ["osascript", "-e", script], capture_output=True, text=True,
                timeout=COMMAND_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            return False, ("macOS did not answer within four seconds — check for an "
                           "Automation permission dialog")
        return proc.returncode == 0, (proc.stdout or proc.stderr).strip()

    def run(self, argv: list[str], timeout: float = COMMAND_TIMEOUT_SECONDS) -> tuple[bool, str]:
        # A caller may ask for a shorter timeout, never a longer one. This is a
        # product deadline, not a suggestion hidden in configuration.
        timeout = max(0.1, min(float(timeout), COMMAND_TIMEOUT_SECONDS))
        try:
            proc = subprocess.run(argv, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            return False, "the system command did not answer within four seconds"
        return proc.returncode == 0, (proc.stdout or proc.stderr).strip()

    def open_url(self, url: str, browser: str | None = None) -> tuple[bool, str]:
        if browser:
            return self.run(["open", "-a", browser, url])
        return self.run(["open", url])

    def keystroke(self, text: str) -> tuple[bool, str]:
        """Type into whatever the system has focused — the dictation path.
        No tree read, no targeting: one keystroke event, ~100 ms."""
        safe = text.replace("\\", "\\\\").replace('"', '\\"')
        return self.osascript(f'tell application "System Events" to keystroke "{safe}"')

    def ax_tree(self):
        """The frontmost app's accessibility tree (MacAXTree on a Mac)."""
        from ..ax import MacAXTree

        return MacAXTree()


class DryRunBridge(MacBridge):
    """Logs exactly what would run on a Mac; executes nothing. Demo/CI/first run."""

    platform = "dry-run"

    def __init__(self) -> None:
        self.calls: list[tuple[str, str]] = []
        self._ax = None

    def osascript(self, script: str) -> tuple[bool, str]:
        self.calls.append(("osascript", script))
        return True, f"[dry-run] osascript: {script[:120]}"

    def run(self, argv: list[str], timeout: float = COMMAND_TIMEOUT_SECONDS) -> tuple[bool, str]:
        self.calls.append(("run", " ".join(argv)))
        return True, f"[dry-run] {' '.join(argv[:4])}"

    def open_url(self, url: str, browser: str | None = None) -> tuple[bool, str]:
        self.calls.append(("open", url))
        if browser:
            self.calls.append(("browser", browser))
        return True, f"[dry-run] open {url}" + (f" in {browser}" if browser else "")

    def keystroke(self, text: str) -> tuple[bool, str]:
        self.calls.append(("keystroke", text))
        return True, f"[dry-run] typed {text!r} into the focused field"

    def ax_tree(self):
        """The deterministic mock window — same interface as the real thing."""
        from ..ax import MockAXTree

        if self._ax is None:
            self._ax = MockAXTree()
        return self._ax
